swagger: '2.0'
info:
  description: API 文档
  version: 1.0.0
  title: API 文档
  termsOfService: ''
  contact:
    name: 编写者
    email: yulefox@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8080'
basePath: /v2
tags:
  - name: host
    description: 主机
    externalDocs:
      description: 更多文档
      url: 'http://sdk.yulefox.com'
  - name: service
    description: 服务
    externalDocs:
      description: 更多文档
      url: 'http://sdk.yulefox.com'
schemes:
  - http
paths:
  '/host/{scope}':
    get:
      tags:
        - host
      summary: 获取指定域的主机列表
      description: 返回主机列表
      operationId: getHostsByScope
      produces:
        - application/json
      parameters:
        - name: scope
          in: path
          description: 主机的作用域
          required: true
          type: string
          enum:
            - all
            - dev
            - pro
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Host'
        '400':
          description: Invalid scope supplied
        '404':
          description: Host not found
definitions:
  Host:
    type: object
    required:
      - id
      - name
      - ip
      - scope
    properties:
      id:
        type: integer
        format: int64
        description: 主机 ID
      name:
        type: string
        description: 主机名称/索引(可以用数字标识)
      ip:
        type: string
        description: 主机 IP 地址
      domain:
        type: string
        description: 域名
      scope:
        type: string
        description: 主机所在子网/域
    xml:
      name: Host
  Service:
    type: object
    required:
      - id
      - host
    properties:
      id:
        type: integer
        format: int64
      host:
        $ref: '#/definitions/Host'
      status:
        type: string
        description: pet status in the store
        enum:
          - available
          - pending
          - sold
    xml:
      name: Pet
externalDocs:
  description: 详细文档
  url: 'http://sdk.yulefox.com'
